/*
 * This file is generated by jOOQ.
 */
package com.jooq.entity.tables


import com.jooq.entity.Public
import com.jooq.entity.keys.PK_DATABASECHANGELOGLOCK
import com.jooq.entity.tables.records.DatabasechangeloglockRecord

import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Databasechangeloglock(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, DatabasechangeloglockRecord>?,
    aliased: Table<DatabasechangeloglockRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<DatabasechangeloglockRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC.DATABASECHANGELOGLOCK</code>
         */
        val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<DatabasechangeloglockRecord> = DatabasechangeloglockRecord::class.java

    /**
     * The column <code>PUBLIC.DATABASECHANGELOGLOCK.ID</code>.
     */
    val ID: TableField<DatabasechangeloglockRecord, Int?> = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>PUBLIC.DATABASECHANGELOGLOCK.LOCKED</code>.
     */
    val LOCKED: TableField<DatabasechangeloglockRecord, Boolean?> = createField(DSL.name("LOCKED"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>PUBLIC.DATABASECHANGELOGLOCK.LOCKGRANTED</code>.
     */
    val LOCKGRANTED: TableField<DatabasechangeloglockRecord, LocalDateTime?> = createField(DSL.name("LOCKGRANTED"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>PUBLIC.DATABASECHANGELOGLOCK.LOCKEDBY</code>.
     */
    val LOCKEDBY: TableField<DatabasechangeloglockRecord, String?> = createField(DSL.name("LOCKEDBY"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<DatabasechangeloglockRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<DatabasechangeloglockRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>PUBLIC.DATABASECHANGELOGLOCK</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>PUBLIC.DATABASECHANGELOGLOCK</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>PUBLIC.DATABASECHANGELOGLOCK</code> table reference
     */
    constructor(): this(DSL.name("DATABASECHANGELOGLOCK"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, DatabasechangeloglockRecord>): this(Internal.createPathAlias(child, key), child, key, DATABASECHANGELOGLOCK, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<DatabasechangeloglockRecord> = PK_DATABASECHANGELOGLOCK
    override fun `as`(alias: String): Databasechangeloglock = Databasechangeloglock(DSL.name(alias), this)
    override fun `as`(alias: Name): Databasechangeloglock = Databasechangeloglock(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Databasechangeloglock = Databasechangeloglock(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Databasechangeloglock = Databasechangeloglock(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, Boolean?, LocalDateTime?, String?> = super.fieldsRow() as Row4<Int?, Boolean?, LocalDateTime?, String?>
}
