---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sample
  namespace: argocd # argocd는 기본적으로 argocd 네임스페이스에서 Application들을 관리한다.
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/banjjoknim/argocd-sample
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/banjjoknim/TIL
    targetRevision: apply-argocd-image-updater
    path: playground/argocd-sample/k8s/test
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # argocd는 기본적으로 argocd 네임스페이스에서 Application들을 관리한다.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true