server:
  port: 8080

spring:
  application:
    name: Spring Cloud Gateway Reactive Sample
    profile: local
    version: v1
    url: http://localhost:8080

  cloud:
    gateway:
      default-filters:
        - AuthorizationHeader # 사용자 지정 인증 필터, NamingRule에 따라 변환된 값을 넣어야 제대로 동작한다. 그렇지 않으면 해당 필터를 찾지 못해 서버가 기동되지 않는다. `기본값 : XXXGatewayFilterFactory -> XXX`
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE # 헤더의 중복을 제거하기 위한 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
      routes:
        - id: server-1
          metadata:
            serviceDescription: Reactive Server 1
            routePath: server-1
          uri: http://localhost:8010
          predicates:
            - Path=/server-1/**
          filters:
            - RewritePath=/server-1/(?<path>.*), /$\{path}
        - id: server-2
          metadata:
            serviceDescription: Reactive Server 2
            routePath: server-2
          uri: http://localhost:8020
          predicates:
            - Path=/server-2/**
          filters:
            - RewritePath=/server-2/(?<path>.*), /$\{path}

logging:
  level:
    org:
      springframework:
        cloud: INFO
      apache:
        http: INFO
    com.banjjoknim: INFO
