POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "banjjoknim",
  "email": "banjjoknim@github.com",
  "phoneNumber": "010-1234-5678"
}

###
GET http://localhost:8080/users/1
