rootProject.name = "TIL"
include("playground:argocd-sample")
include("playground:ddd-start2")
include("playground:graphql-federation")
include("playground:graphql-kotlin")
include("playground:jackson")
include("playground:learn-with-making-clean-architecture")
include("playground:playground")
include("playground:solid-design-pattern-sample")
include("playground:spring-boot-test-sample")
include("playground:spring-cloud-open-feign")
include("playground:spring-event")
include("playground:spring-image")
include("playground:spring-jooq-liquibase")
include("playground:spring-multi-module")
include("playground:spring-redis")
include("playground:spring-security")
include("playground:spring-server-sent-event")
