/*
 * This file is generated by jOOQ.
 */
package com.jooq.entity.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Databasechangeloglock(
    val id: Int? = null,
    val locked: Boolean? = null,
    val lockgranted: LocalDateTime? = null,
    val lockedby: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Databasechangeloglock (")

        sb.append(id)
        sb.append(", ").append(locked)
        sb.append(", ").append(lockgranted)
        sb.append(", ").append(lockedby)

        sb.append(")")
        return sb.toString()
    }
}
