/*
 * This file is generated by jOOQ.
 */
package com.jooq.entity.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class LiquibaseInit(
    val id: Int? = null,
    val author: String? = null,
    val description: String? = null,
    val initAt: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("LiquibaseInit (")

        sb.append(id)
        sb.append(", ").append(author)
        sb.append(", ").append(description)
        sb.append(", ").append(initAt)

        sb.append(")")
        return sb.toString()
    }
}
