spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

