/*
 * This file is generated by jOOQ.
 */
package com.jooq.entity.tables.references


import com.jooq.entity.tables.Databasechangelog
import com.jooq.entity.tables.Databasechangeloglock
import com.jooq.entity.tables.LiquibaseInit
import com.jooq.entity.tables.Order



/**
 * The table <code>PUBLIC.DATABASECHANGELOG</code>.
 */
val DATABASECHANGELOG: Databasechangelog = Databasechangelog.DATABASECHANGELOG

/**
 * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
 */
val DATABASECHANGELOGLOCK: Databasechangeloglock = Databasechangeloglock.DATABASECHANGELOGLOCK

/**
 * The table <code>PUBLIC.LIQUIBASE_INIT</code>.
 */
val LIQUIBASE_INIT: LiquibaseInit = LiquibaseInit.LIQUIBASE_INIT

/**
 * The table <code>PUBLIC.ORDER</code>.
 */
val ORDER: Order = Order.ORDER
