apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/banjjoknim/argocd-sample
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: latest
  name: argocd-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-sample
    server: https://kubernetes.default.svc
  project: default
  source:
    path: playground/argocd-sample/k8s/argocd-sample # ArgoCD Image Updater는 Kustomize or Helm type 중 하나여야 한다.
    repoURL: git@github.com:banjjoknim/TIL # https://github.com/banjjoknim/TIL
    targetRevision: apply-argocd-image-updater-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true